apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ProfileSite"
  annotations:
    github.com/project-slug: solthoth/ProfileSite
    backstage.io/techdocs-ref: dir:.
  tags:
    - docker
    - k8s
    - typescript
    - nestjs
  links: []
spec:
  type: service
  lifecycle: production
  system: "system:default/payments"
  owner: "group:default/core-tribe-checkout"
